# Generated by Django 4.1 on 2024-10-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('CALCA', 'Casacos'), ('CASACO', 'Casacos'), ('CAMISA', 'Camisas'), ('TENIS', 'Tênis')], default='', max_length=100),
        ),
    ]
