# Generated by Django 4.1 on 2024-10-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='poblicada',
            field=models.BooleanField(default=False),
        ),
    ]
