# Generated by Django 4.1 on 2024-10-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotografia',
            new_name='data_produto',
        ),
    ]
