# Generated by Django 4.1 on 2024-11-03 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0010_alter_fotografia_data_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
